spring:
  jackson:
    default-property-inclusion: NON_NULL
  banner:
    location: classpath:banner.txt
  data:
    mongodb:
      uri: ${MONGODB_TEST_URL}
  web:
    resources:
      add-mappings: true